package vismanet

type Employees []Employee

type Employee struct {
	SalutationID               string `csv:"salutationid"`
	Salutation                 string `csv:"salutation"`
	Initials                   string `csv:"initials"`
	FirstName                  string `csv:"firstname"`
	Nickname                   string `csv:"nickname"`
	NameUsageEn                string `csv:"nameusage_en"`
	NameUsage                  string `csv:"nameusage"`
	Namecode                   string `csv:"namecode"`
	BirthName                  string `csv:"birthname"`
	PrefixBirthName            string `csv:"prefixbirthname"`
	FormattedName              string `csv:"formattedname"`
	DateOfBirth                Date   `csv:"dateofbirth"`
	Gender                     string `csv:"gender"`
	NationalityEn              string `csv:"nationality_en"`
	Nationality                string `csv:"nationality"`
	CorrAddressEn              string `csv:"corraddress_en"`
	CorrAddress                string `csv:"corraddress"`
	TitleBeforeEn              string `csv:"titlebefore_en"`
	TitleBefore                string `csv:"titlebefore"`
	TitleAfterEn               string `csv:"titleafter_en"`
	TitleAfter                 string `csv:"titleafter"`
	LanguageEn                 string `csv:"language_en"`
	Language                   string `csv:"language"`
	PartnerName                string `csv:"partnername"`
	PrefixPartnerName          string `csv:"prefixpartnername"`
	MaritalStatusID            string `csv:"maritalstatusid"`
	MaritalStatus              string `csv:"maritalstatus"`
	OfficialDate               Date   `csv:"officialdate"`
	EmployeeGroupID            string `csv:"employeegroupid"`
	EmployeeGroupNameEn        string `csv:"employeegroupname_en"`
	EmployeeGroupName          string `csv:"employeegroupname"`
	IsManager                  string `csv:"ismanager"`
	CompanyID                  string `csv:"companyid"`
	CompanyName                string `csv:"companyname"`
	BoardNumber                string `csv:"boardnumber"`
	SicknessStreet             string `csv:"sicknessstreet"`
	SicknessHouseNumber        string `csv:"sicknesshousenumber"`
	SicknessHouseNumberExt     string `csv:"sicknesshousenumberext"`
	SicknessZipcode            string `csv:"sicknesszipcode"`
	SicknessCity               string `csv:"sicknesscity"`
	SicknessCountryEn          string `csv:"sicknesscountry_en"`
	SicknessCountry            string `csv:"sicknesscountry"`
	PostalStreet               string `csv:"postalstreet"`
	PostalHouseNumber          string `csv:"postalhousenumber"`
	PostalHouseNumberExt       string `csv:"postalhousenumberext"`
	PostalZipCode              string `csv:"postalzipcode"`
	PostalCity                 string `csv:"postalcity"`
	PostalCountryEn            string `csv:"postalcountry_en"`
	PostalCountry              string `csv:"postalcountry"`
	HomeStreet                 string `csv:"homestreet"`
	HomeHouseNumber            string `csv:"homehousenumber"`
	HomeHouseNumberext         string `csv:"homehousenumberext"`
	HomeZipCode                string `csv:"homezipcode"`
	HomeCity                   string `csv:"homecity"`
	HomeCountryEn              string `csv:"homecountry_en"`
	HomeCountry                string `csv:"homecountry"`
	OtherAddressesEn           string `csv:"otheraddresses_en"`
	OtherAddresses             string `csv:"otheraddresses"`
	HomeEmailAddress           string `csv:"homeemailaddress"`
	BusinessEmailAddress       string `csv:"businessemailaddress"`
	HomewebEmailAddress        string `csv:"homewebemailaddress"`
	Businesswebemailaddress    string `csv:"businesswebemailaddress"`
	OtherEmailAddressesEn      string `csv:"otheremailaddresses_en"`
	OtherEmailaddresses        string `csv:"otheremailaddresses"`
	HomePhoneNumber            string `csv:"homephonenumber"`
	OfficeMobilePhoneNumber    string `csv:"officemobilephonenumber"`
	HomeFaxPhoneNumber         string `csv:"homefaxphonenumber"`
	PrivateMobilePhoneNumber   string `csv:"privatemobilephonenumber"`
	OfficetelPhoneNumber       string `csv:"officetelphonenumber"`
	OfficeextPhoneNumber       string `csv:"officeextphonenumber"`
	OfficefaxPhoneNumber       string `csv:"officefaxphonenumber"`
	SecretaryPhoneNumber       string `csv:"secretaryphonenumber"`
	SicknessAddressPhoneNumber string `csv:"sicknessaddressphonenumber"`
	EmergencyPhoneNumber       string `csv:"emergencyphonenumber"`
	OtherPhoneNumbersEn        string `csv:"otherphonenumbers_en"`
	OtherPhoneNumbers          string `csv:"otherphonenumbers"`
	ODPOrgID                   string `csv:"odporgid"`
	EmployeeID                 string `csv:"employeeid"`
	ExistenceStartUTC          string `csv:"existencestartutc"`
}

type Contracts []Contract

type Contract struct {
	StartDate                Date    `csv:"startdate"`
	EndDate                  Date    `csv:"enddate"`
	Probation                Date    `csv:"probation"`
	ContractTypeIndicationEN string  `csv:"contracttypeindication_en"`
	ContractTypeIndicationNL string  `csv:"contracttypeindication_nl"`
	EndReason                string  `csv:"endreason"`
	EndReasonNameEN          string  `csv:"endreasonname_en"`
	EndReasonName            string  `csv:"endreasonname"`
	BaseSubContractID        string  `csv:"basesubcontractid"`
	CAO                      string  `csv:"cao"`
	ExternalCAOCode          string  `csv:"externalcaocode"`
	TypeEn                   string  `csv:"type_en"`
	Type                     string  `csv:"type"`
	CostCenterEN             string  `csv:"costcenter_en"`
	CostCenter               string  `csv:"costcenter"`
	OrgUnit                  string  `csv:"orgunit"`
	OrgunitNameEN            string  `csv:"orgunitname_en"`
	OrgUnitName              string  `csv:"orgunitname"`
	ExtDepartmentID          string  `csv:"extdepartmentid"`
	ExtDepartmentNameEN      string  `csv:"extdepartmentname_en"`
	ExtDepartmentName        string  `csv:"extdepartmentname"`
	EmpType                  string  `csv:"emptype"`
	EmpTypeNameEN            string  `csv:"emptypename_en"`
	EmpTypeName              string  `csv:"emptypename"`
	ExpertiseID              string  `csv:"expertiseid"`
	ExpertiseNameEN          string  `csv:"expertisename_en"`
	ExpertiseName            string  `csv:"expertisename"`
	CostUnitEN               string  `csv:"costunit_en"`
	CostUnit                 string  `csv:"costunit"`
	FunctionID               string  `csv:"functionid"`
	FunctionNameEN           string  `csv:"functionname_en"`
	FunctionName             string  `csv:"functionname"`
	RosterID                 string  `csv:"rosterid"`
	PTFactor                 float64 `csv:"ptfactor"`
	WeekHoursFixed           float64 `csv:"weekhoursfixed"`
	WeekHoursVar             float64 `csv:"weekhoursvar"`
	NormalHours              float64 `csv:"normalhours"`
	ScaleTypeEN              string  `csv:"scaletype_en"`
	ScaleType                string  `csv:"scaletype"`
	Scale                    string  `csv:"scale"`
	Step                     string  `csv:"step"`
	StepName                 string  `csv:"stepname"`
	GarScaleTypeEN           string  `csv:"garscaletype_en"`
	GarScaleType             string  `csv:"garscaletype"`
	GarScale                 string  `csv:"garscale"`
	GarStep                  string  `csv:"garstep"`
	GarStepName              string  `csv:"garstepname"`
	CatsScale                string  `csv:"catsscale"`
	CatsScaleName            string  `csv:"catsscalename"`
	CatsScaleID              string  `csv:"catsscaleid"`
	CatsRSPFactor            string  `csv:"catsrspfactor"`
	SalaryHour               float64 `csv:"salaryhour"`
	GarSalaryHour            float64 `csv:"garsalaryhour"`
	SalaryHourORT            float64 `csv:"salaryhourort"`
	SalaryHourTravel         float64 `csv:"salaryhourtravel"`
	SalaryHourExtra          float64 `csv:"salaryhourextra"`
	SalaryType               string  `csv:"salarytype"`
	Distance                 string  `csv:"distance"`
	MaxDistance              string  `csv:"maxdistance"`
	DaySPW                   string  `csv:"dayspw"`
	TariffID                 string  `csv:"tariffid"`
	TariffNameEN             string  `csv:"tariffname_en"`
	TariffName               string  `csv:"tariffname"`
	PublicTransportRegID     string  `csv:"publictransportregid"`
	PublicTransportRegNameEN string  `csv:"publictransportregname_en"`
	PublicTransportRegName   string  `csv:"publictransportregname"`
	PublicTransportUnits     string  `csv:"publictransportunits"`
	IsPooler                 string  `csv:"ispooler"`
	InsuranceType            string  `csv:"insurancetype"`
	InsuranceTypeNameEN      string  `csv:"insurancetypename_en"`
	InsuranceTypeName        string  `csv:"insurancetypename"`
	FinanceSource            string  `csv:"financesource"`
	FinanceSourceNameEN      string  `csv:"financesourcename_en"`
	FinanceSourceName        string  `csv:"financesourcename"`
	ODPOrgID                 string  `csv:"odporgid"`
	EmployeeID               string  `csv:"employeeid"`
	ContractID               string  `csv:"contractid"`
	SubContractID            string  `csv:"subcontractid"`
	ExistenceStartUTC        string  `csv:"existencestartutc"`
	NickName                 string  `csv:"nickname"`
	BirthName                string  `csv:"birthname"`
	PrefixBirthName          string  `csv:"prefixbirthname"`
	FormattedName            string  `csv:"formattedname"`
	DateOfBirth              Date    `csv:"dateofbirth"`
	Gender                   string  `csv:"gender"`
	ManagerUserID            string  `csv:"manageruserid"`
	ManagerName              string  `csv:"managername"`
}
